[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.ruff.lint]
select = ["B", "C4", "E", "F", "N", "I", "W", "UP"]
ignore = ["B017", "F403", "F405", "E501", "E402", "Q000", "Q003"]

[tool.isort]
profile = "black"
multi_line_output = 3
force_sort_within_sections = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
